---
- name: Deploy mouse-grabr script on /Desktop
  hosts: thRasps
  user: sam
  gather_facts: no
  tasks:
    - name: Ping all devices
      ping:
      register: ping_result
      failed_when: ping_result is undefined # Mark unresponsive hosts as failed

    - name: Copy mouse-grabr.py script to Desktop
      ansible.builtin.copy:
        src: /Users/samuel/htdocs/tryhard/websocket-demo/mouse-grabr.py
        dest: /home/sam/Desktop/mouse-grabr.py
        owner: sam
        mode: "0755"
      when: ping_result is not failed
