---
- name: Deploy and launch mouse-grabr script
  hosts: thRasps
  user: sam
  gather_facts: no
  tasks:
    - name: Ping all devices
      ping:
      register: ping_result
      failed_when: ping_result is undefined # Mark unresponsive hosts as failed

    - name: Copy mouse-grabr.py script to Desktop
      ansible.builtin.copy:
        src: /Users/samuel/htdocs/tryhard/websocket-demo/mouse-grabr.py
        dest: /home/sam/Desktop/mouse-grabr.py
        owner: sam
        mode: "0755"
      when: ping_result is not failed

    - name: Launch mouse-grabr.py using python3
      ansible.builtin.shell: |
        nohup python3 /home/sam/Desktop/mouse-grabr.py simulate &
      args:
        executable: /bin/bash
      when: ping_result is not failed
