---
- name: Terminate all running mouse-grabr scripts
  hosts: thRasps
  user: sam
  gather_facts: no
  tasks:
    - name: Find running mouse-grabr.py processes
      ansible.builtin.shell: pgrep -f mouse-grabr.py
      register: mouse_grabr_processes
      ignore_errors: true

    - name: Terminate mouse-grabr.py processes if found
      ansible.builtin.shell: kill -9 {{ item }}
      with_items: "{{ mouse_grabr_processes.stdout_lines }}"
      when: mouse_grabr_processes.stdout_lines is defined and mouse_grabr_processes.stdout_lines|length > 0

    - name: Confirm no mouse-grabr.py processes are running
      ansible.builtin.shell: pgrep -f mouse-grabr.py
      register: confirmation
      ignore_errors: true

    - name: Ensure all mouse-grabr processes have been terminated
      ansible.builtin.debug:
        msg: "All mouse-grabr.py processes terminated successfully."
      when: confirmation.stdout_lines is not defined or confirmation.stdout_lines|length == 0

    - name: Warn if processes are still running
      ansible.builtin.debug:
        msg: "Some mouse-grabr.py processes could not be terminated: {{ confirmation.stdout_lines }}"
      when: confirmation.stdout_lines is defined and confirmation.stdout_lines|length > 0
