---
- name: Ping, update, and prepare hosts for mouse-grabr
  hosts: thRasps
  user: sam
  gather_facts: no
  vars:
    ansible_become_password: "&é12"
  tasks:
    - name: Ping all devices and mark responsive hosts
      ping:
      register: ping_result
      failed_when: ping_result is undefined # Mark unresponsive hosts as failed

    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: yes
      when: ping_result is not failed
      become: yes

    - name: Install python3-websockets
      ansible.builtin.apt:
        name: python3-websockets
        state: present
      when: ping_result is not failed
      become: yes
