---
- name: Shutdown responsive hosts
  hosts: thRasps
  user: sam
  gather_facts: no
  vars:
    ansible_become_password: { { secrets.raspRootPwd } }
  tasks:
    - name: Ping all devices and mark responsive hosts
      ping:
      register: ping_result
      failed_when: ping_result is undefined # Mark unresponsive hosts as failed

    - name: Shutdown responsive hosts
      ansible.builtin.shell: |
        sudo shutdown now
      when: ping_result is not failed
      become: yes
